# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_detail', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='task start')),
                ('end_date', models.DateTimeField(verbose_name='task end')),
            ],
        ),
    ]
