# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateTimeField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
